spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}4205d6d9bfe258e11075e51394fef9e2ba03ba419a8126a3d5969c4c8ff58ce1'

token:
  expiration_time: 864000000
  secret: user_token

gateway:
  ip: 192.168.0.8